ans_dict = {
    "In which part of your body would you find the cruciate ligament?": "Knee",
    "What is the name of the main antagonist in the Shakespeare play Othello?": "lago",
    "What element is denoted by the chemical symbol Sn in the periodic table?": "Tin",
    "What is the name of the 1976 film about the Watergate scandal, starring Robert Redford and Dustin Hoffman?": "All of them",
    "How many of Henry VIII's wives were called Catherine?": "3",
    "Which comedian was the second permanent host of Never Mind the Buzzcocks after Mark Lamarr?": "Simon Amstell",
    "Which popular video game franchise has released games with the subtitles World At War and Black Ops?": "Call of Duty",
    "In what US State is the city Nashville?": "Tenessee",
    "Which rock band was founded by Trent Reznor in 1988?": "9inch nails",
    "What is the currency of Denmark?": "Krone",
    "Which Tennis Grand Slam is played on a clay surface?": "The French Open",
    "In which European country would you find the Rijksmuseum?": "Netherlands",
    "How many films have Al Pacino and Robert De Niro appeared in together?": "4",
    "What was the old name for a Snickers bar before it changed in 1990?": "Marathon",
    "Who was the head of state in Japan during the second world war?": "Emperor Hirohito",
    "What is the smallest planet in our solar system?": "Mecury",
    "Who wrote the novels Gone Girl and Sharp Objects?": "Gillian Flynn",
    "Which legendary surrealist artist is famous for painting melting clocks?": "Salvador Dali",
    "Which football club plays its home games at Loftus Road?": "Queens Park Rangers",
    "Continental United States has 4 time zones, can you name them?": "Pacific, Mountain, Central, Eastern",
    "What was the Turkish city of Istanbul called before 1930?": "Constantinople",
    "From which US city do the band The Killers originate?": "Las Vegas",
    "Name the Coffee shop in US sitcom Friends": "Central Park",
    "How many human players are there on each side in a polo match?": "4",
    "In what year did Tony Blair become British Prime Minister?": "1997",
    "How many times has England won the men's football World Cup?": "once",
    "What is the capital of New Zealand?": "Wellington",
    "Street artist Banksy is originally associated with which British city?": "Bristol",
    "From what grain is the Japanese spirit Sake made?": "Rice",
}
questions = ["In which part of your body would you find the cruciate ligament?",
"What is the name of the main antagonist in the Shakespeare play Othello?",
"What element is denoted by the chemical symbol Sn in the periodic table?",
"What is the name of the 1976 film about the Watergate scandal, starring Robert Redford and Dustin Hoffman?",
"How many of Henry VIII's wives were called Catherine?",
"Which comedian was the second permanent host of Never Mind the Buzzcocks after Mark Lamarr?",
"Which popular video game franchise has released games with the subtitles World At War and Black Ops?",
"In what US State is the city Nashville?",
"Which rock band was founded by Trent Reznor in 1988?",
"What is the currency of Denmark?",
"Which Tennis Grand Slam is played on a clay surface?",
"In which European country would you find the Rijksmuseum?",
"How many films have Al Pacino and Robert De Niro appeared in together?",
"What was the old name for a Snickers bar before it changed in 1990?",
"Who was the head of state in Japan during the second world war?",
"What is the smallest planet in our solar system?",
"Who wrote the novels Gone Girl and Sharp Objects?",
"Which legendary surrealist artist is famous for painting melting clocks?",
"Which football club plays its home games at Loftus Road?",
"Continental United States has 4 time zones, can you name them?",
"What was the Turkish city of Istanbul called before 1930?",
"From which US city do the band The Killers originate?",
"Name the Coffee shop in US sitcom Friends",
"How many human players are there on each side in a polo match?",
"In what year did Tony Blair become British Prime Minister?",
"How many times has England won the men's football World Cup?",
"What is the capital of New Zealand?",
"Street artist Banksy is originally associated with which British city?",
"From what grain is the Japanese spirit Sake made?"
]
